# Generated by Django 4.1.6 on 2023-04-03 14:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_gallery_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gallery_link",
        ),
    ]
